export type CountriesInId = {
  [key: string]: {label: string; code2: string;};
};
export const countriesInId: CountriesInId = {
  GER: { label: 'jerman', code2: 'DE' },
  BRA: { label: 'brasil', code2: 'BR' },
  AZE: { label: 'azerbaijan', code2: 'AZ' },
  HUN: { label: 'hongaria', code2: 'HU' },
  COL: { label: 'kolombia', code2: 'CO' },
  POL: { label: 'polandia', code2: 'PL' },
  GRE: { label: 'yunani', code2: 'GR' },
  RSA: { label: 'afrika selatan', code2: 'ZA' },
  CAT: { label: 'catalunya', code2: '' },
  ESP: { label: 'spanyol', code2: 'ES' },
  ANG: { label: 'angola', code2: 'AO' },
  MLI: { label: 'mali', code2: 'ML' },
  CMR: { label: 'kamerun', code2: 'CM' },
  QAT: { label: 'qatar', code2: 'QA' },
  LBY: { label: 'libya', code2: 'LY' },
  EQG: { label: 'guinea khatulistiwa', code2: 'GQ' },
  WAL: { label: 'wales', code2: 'GB-WLS' },
  CHN: { label: 'tiongkok', code2: 'CN' },
  POR: { label: 'portugal', code2: 'PT' },
  CHI: { label: 'chili', code2: 'CL' },
  MNE: { label: 'montenegro', code2: 'ME' },
  URS: { label: 'uni soviet', code2: '' },
  MLT: { label: 'malta', code2: 'MT' },
  OMA: { label: 'oman', code2: 'OM' },
  IND: { label: 'india', code2: 'IN' },
  LAO: { label: 'laos', code2: 'LA' },
  AUT: { label: 'austria', code2: 'AT' },
  SRB: { label: 'serbia', code2: 'RS' },
  ZAM: { label: 'zambia', code2: 'ZM' },
  PAN: { label: 'panama', code2: 'PA' },
  BEL: { label: 'belgia', code2: 'BE' },
  ARG: { label: 'argentina', code2: 'AR' },
  SYR: { label: 'suriah', code2: 'SY' },
  DJI: { label: 'djibouti', code2: '' },
  KOR: { label: 'korea selatan', code2: 'KR' },
  GUM: { label: 'guam', code2: 'GU' },
  NED: { label: 'belanda', code2: 'NL' },
  MAC: { label: 'makau', code2: 'MO' },
  UAE: { label: 'uni emirat arab', code2: 'AE' },
  HKG: { label: 'hong kong', code2: 'HK' },
  ISR: { label: 'israel', code2: 'IL' },
  PUR: { label: 'puerto riko', code2: 'PR' },
  AFG: { label: 'afganistan', code2: 'AF' },
  COD: { label: 'republik demokratik kongo', code2: 'CD' },
  CHA: { label: 'chad', code2: 'TD' },
  THA: { label: 'thailand', code2: 'TH' },
  SDN: { label: 'sudan', code2: 'SD' },
  BHR: { label: 'bahrain', code2: 'BH' },
  ARM: { label: 'armenia', code2: 'AM' },
  SLE: { label: 'sierra leone', code2: 'SL' },
  TJK: { label: 'tajikistan', code2: 'TJ' },
  VIE: { label: 'vietnam', code2: 'VN' },
  GRN: { label: 'grenada', code2: 'GD' },
  MYA: { label: 'myanmar', code2: 'MM' },
  TPE: { label: 'tionghoa taipei', code2: 'TW-TPE' },
  VAN: { label: 'vanuatu', code2: 'VU' },
  ANT: { label: 'antillen belanda', code2: '' },
  LBR: { label: 'liberia', code2: 'LR' },
  BEN: { label: 'benin', code2: 'BJ' },
  LIB: { label: 'lebanon', code2: 'LB' },
  MSR: { label: 'montserrat', code2: 'MS' },
  USA: { label: 'amerika serikat', code2: 'US' },
  MEX: { label: 'meksiko', code2: 'MX' },
  TRI: { label: 'trinidad dan tobago', code2: 'TT' },
  BHU: { label: 'bhutan', code2: 'BT' },
  TCA: { label: 'kepulauan turks dan caicos', code2: 'TC' },
  BOT: { label: 'botswana', code2: 'BW' },
  KAZ: { label: 'kazakhstan', code2: 'KZ' },
  ZIM: { label: 'zimbabwe', code2: 'ZW' },
  SLV: { label: 'el salvador', code2: 'SV' },
  YUG: { label: 'yugoslavia', code2: 'YU' },
  MKD: { label: 'makedonia utara', code2: 'MK' },
  GUI: { label: 'guinea', code2: 'GN' },
  JOR: { label: 'yordania', code2: 'JO' },
  LIE: { label: 'liechtenstein', code2: 'LI' },
  CYP: { label: 'siprus', code2: 'CY' },
  REU: { label: 'réunion', code2: 'RE' },
  NGA: { label: 'nigeria', code2: 'NG' },
  NEP: { label: 'nepal', code2: 'NP' },
  BFA: { label: 'burkina faso', code2: 'BF' },
  JPN: { label: 'jepang', code2: 'JP' },
  CZE: { label: 'republik ceko', code2: 'CZ' },
  EST: { label: 'estonia', code2: 'EE' },
  TCH: { label: 'cekoslowakia', code2: '' },
  BIH: { label: 'bosnia dan herzegovina', code2: 'BA' },
  VEN: { label: 'venezuela', code2: 'VE' },
  CAM: { label: 'kamboja', code2: 'KH' },
  SWZ: { label: 'eswatini', code2: 'SZ' },
  SEN: { label: 'senegal', code2: 'SN' },
  TLS: { label: 'timor leste', code2: 'TL' },
  SSD: { label: 'sudan selatan', code2: 'SS' },
  NAM: { label: 'namibia', code2: 'NA' },
  PHI: { label: 'filipina', code2: 'PH' },
  JAM: { label: 'jamaika', code2: 'JM' },
  NIU: { label: 'niue', code2: 'NU' },
  SUR: { label: 'suriname', code2: 'SR' },
  NCA: { label: 'nikaragua', code2: 'NI' },
  GYF: { label: 'guyana prancis', code2: 'GF' },
  CUW: { label: 'curaçao', code2: 'CW' },
  SVN: { label: 'slovenia', code2: 'SI' },
  DEN: { label: 'denmark', code2: 'DK' },
  PNG: { label: 'papua nugini', code2: 'PG' },
  FIN: { label: 'finlandia', code2: 'FI' },
  ERI: { label: 'eritrea', code2: 'ER' },
  GEO: { label: 'georgia', code2: 'GE' },
  LES: { label: 'lesotho', code2: 'LS' },
  LTU: { label: 'lituania', code2: 'LT' },
  NCY: { label: 'siprus utara', code2: '' },
  SOM: { label: 'somalia', code2: 'SO' },
  GUY: { label: 'guyana', code2: 'GY' },
  KGZ: { label: 'kirgizstan', code2: 'KG' },
  IRQ: { label: 'irak', code2: 'IQ' },
  LBN: { label: 'lebanon', code2: 'LB' },
  FSM: { label: 'mikronesia', code2: 'FM' },
  BLR: { label: 'belarus', code2: 'BY' },
  NZL: { label: 'selandia baru', code2: 'NZ' },
  CAY: { label: 'kepulauan cayman', code2: 'KY' },
  TGA: { label: 'tonga', code2: 'TO' },
  SRI: { label: 'sri lanka', code2: 'LK' },
  STP: { label: 'são tomé dan príncipe', code2: '' },
  VGB: { label: 'kepulauan virgin britania raya', code2: '' },
  CPV: { label: 'tanjung verde', code2: 'CV' },
  ASA: { label: 'samoa amerika', code2: 'AS' },
  VIN: { label: 'saint vincent dan grenadine', code2: 'VC' },
  GPE: { label: 'liga guadeloupe', code2: '' },
  AIA: { label: 'anguilla', code2: 'AI' },
  COM: { label: 'komoro', code2: 'KM' },
  MCO: { label: 'monako', code2: 'MC' },
  CIV: { label: 'pantai gading', code2: 'CI' },
  ALB: { label: 'albania', code2: 'AL' },
  MOZ: { label: 'mozambik', code2: 'MZ' },
  BDI: { label: 'burundi', code2: 'BI' },
  PAK: { label: 'pakistan', code2: 'PK' },
  MTN: { label: 'mauritania', code2: 'MR' },
  PLE: { label: 'palestina', code2: 'PS' },
  GNB: { label: 'guinea-bissau', code2: 'GW' },
  SUI: { label: 'swiss', code2: 'CH' },
  ITA: { label: 'italia', code2: 'IT' },
  UKR: { label: 'ukraina', code2: 'UA' },
  CTA: { label: 'republik afrika tengah', code2: 'CF' },
  NIR: { label: 'irlandia utara', code2: 'GB-NIR' },
  UGA: { label: 'uganda', code2: 'UG' },
  IRN: { label: 'iran', code2: 'IR' },
  TCD: { label: 'chad', code2: 'TD' },
  SEY: { label: 'seychelles', code2: 'SC' },
  SIN: { label: 'singapura', code2: 'SG' },
  KSA: { label: 'arab saudi', code2: 'SA' },
  CUB: { label: 'kuba', code2: 'CU' },
  UZB: { label: 'uzbekistan', code2: 'UZ' },
  PLW: { label: 'palau', code2: 'PW' },
  LVA: { label: 'latvia', code2: 'LV' },
  VSO: { label: 'vietnam selatan', code2: '' },
  MRI: { label: 'mauritius', code2: 'MU' },
  GUA: { label: 'guatemala', code2: 'GT' },
  ALG: { label: 'aljazair', code2: 'DZ' },
  MDA: { label: 'moldova', code2: 'MD' },
  VIR: { label: 'kepulauan virgin amerika serikat', code2: 'VI' },
  ZAN: { label: 'zanzibar', code2: '' },
  KOS: { label: 'kosovo', code2: 'XK' },
  MNG: { label: 'mongolia', code2: 'MN' },
  FRA: { label: 'perancis', code2: 'FR' },
  SKN: { label: 'saint kitts dan nevis', code2: 'KN' },
  SCO: { label: 'skotlandia', code2: 'GB-SCT' },
  DOM: { label: 'dominika', code2: 'DM' },
  MAR: { label: 'maroko', code2: 'MA' },
  DMA: { label: 'dominika', code2: 'DM' },
  MDV: { label: 'maladewa', code2: 'MV' },
  YEM: { label: 'yaman', code2: 'YE' },
  COK: { label: 'kepulauan cook', code2: 'CK' },
  NMI: { label: 'kepulauan mariana utara', code2: 'MP' },
  MAD: { label: 'madagaskar', code2: 'MG' },
  KVX: { label: 'kosovo', code2: 'XK' },
  CRO: { label: 'kroasia', code2: 'HR' },
  CGO: { label: 'republik kongo', code2: 'CG' },
  MAS: { label: 'malaysia', code2: 'MY' },
  ARU: { label: 'aruba', code2: 'AW' },
  AND: { label: 'andorra', code2: 'AD' },
  RUS: { label: 'rusia', code2: 'RU' },
  ABK: { label: 'abkhazia', code2: '' },
  BER: { label: 'bermuda', code2: 'BM' },
  PER: { label: 'peru', code2: 'PE' },
  SWE: { label: 'swedia', code2: 'SE' },
  SVK: { label: 'slowakia', code2: 'SK' },
  BAN: { label: 'bangladesh', code2: 'BD' },
  EGY: { label: 'mesir', code2: 'EG' },
  AUS: { label: 'australia', code2: 'AU' },
  GDR: { label: 'jerman ur', code2: '' },
  SOL: { label: 'kepulauan solomon', code2: 'SB' },
  IRL: { label: 'republik irlandia', code2: 'IE' },
  NOR: { label: 'norwegia', code2: 'NO' },
  GAB: { label: 'gabon', code2: 'GA' },
  BOL: { label: 'bolivia', code2: 'BO' },
  FRO: { label: 'slowakia', code2: 'SK' },
  IDN: { label: 'indonesia', code2: 'ID' },
  PRK: { label: 'korea utara', code2: 'KP' },
  BAH: { label: 'bahama', code2: 'BS' },
  NIG: { label: 'niger', code2: 'NE' },
  SMT: { label: 'saint-martin', code2: '' },
  ETH: { label: 'etiopia', code2: 'ET' },
  GAM: { label: 'gambia', code2: 'GM' },
  LCA: { label: 'saint lucia', code2: 'LC' },
  RWA: { label: 'rwanda', code2: 'RW' },
  NCL: { label: 'kaledonia baru', code2: 'NC' },
  KIR: { label: 'kiribati', code2: 'KI' },
  BUL: { label: 'bulgaria', code2: 'BG' },
  ENG: { label: 'inggris', code2: 'GB-ENG' },
  TKM: { label: 'turkmenistan', code2: 'TM' },
  CRC: { label: 'kosta rika', code2: 'CR' },
  TUR: { label: 'turki', code2: 'TR' },
  LUX: { label: 'luksemburg', code2: 'LU' },
  SMR: { label: 'san marino', code2: 'SM' },
  ISL: { label: 'islandia', code2: 'IS' },
  KUW: { label: 'kuwait', code2: 'KW' },
  GBR: { label: 'britania raya', code2: 'GB' },
  CAN: { label: 'kanada', code2: 'CA' },
  TAN: { label: 'tanzania', code2: 'TZ' },
  TAH: { label: 'tahiti', code2: 'PF' },
  BRB: { label: 'barbados', code2: 'BB' },
  SXM: { label: 'sint maarten', code2: 'SX' },
  HON: { label: 'honduras', code2: 'HN' },
  FIJ: { label: 'fiji', code2: 'FJ' },
  SAM: { label: 'samoa', code2: 'WS' },
  MTQ: { label: 'ligue de football de martinique', code2: '' },
  TUN: { label: 'tunisia', code2: 'TN' },
  KEN: { label: 'kenya', code2: 'KE' },
  BRU: { label: 'brunei', code2: 'BN' },
  ECU: { label: 'ekuador', code2: 'EC' },
  ATG: { label: 'antigua dan barbuda', code2: 'AG' },
  MWI: { label: 'malawi', code2: 'MW' },
  BLZ: { label: 'belize', code2: 'BZ' },
  GIB: { label: 'gibraltar', code2: 'GI' },
  TOG: { label: 'togo', code2: 'TG' },
  ROU: { label: 'rumania', code2: 'RO' },
  URU: { label: 'uruguay', code2: 'UY' },
  TUV: { label: 'tuvalu', code2: 'TV' },
  PAR: { label: 'paraguay', code2: 'PY' },
  PAL: { label: 'mandat palestina', code2: '' },
  HAI: { label: 'haiti', code2: 'HT' },
  GRL: { label: 'greenland', code2: 'GL' },
  GHA: { label: 'ghana', code2: 'GH' },
  RAE: { label: 'raetia', code2: '' }
};
